apiVersion: v1
name: otp
version: 'v1'
appVersion: 'release-1.0.0'
description: Open Trip Planner
keywords:
- otp
sources:
- https://github.com/entur/opentripplanner
maintainers:
- name: 'Team: ror'
  email: team.rutedata@entur.org
engine: gotpl
