env: staging-c2

replicas: 3

horizontalPodAutoscaler:
  enabled: true
  maxReplicas: 40
  minReplicas: 2
  targetCPUUtilizationPercentage: 90

rollingUpdate:
  maxSurge: 3
  maxUnavailable: 1

environmentValues:
  mardukGcpBaseName: "gs://marduk-stage/"

cronjobRedeployOtp:
  environmentValues:
    cloudsdkCoreProject: radon-1287

cronjobRedeployGraphBuilder:
  mardukBucket: marduk-stage
  mardukStorageSecretName: marduk-radon-storage-key

secretMounts:
  - name: marduk-key
    mountPath: /etc/marduk/marduk-blobstore-credentials.json
    subPath: marduk-blobstore-credentials.json
    secretName: marduk-radon-storage-key
    readOnly: true

configuration:
  siriVMUpdater: https://api.staging.entur.io/realtime/v1/services
  siriETUpdater: https://api.staging.entur.io/realtime/v1/services
  siriSXUpdater: https://api.staging.entur.io/realtime/v1/services?maxSize=50
  useFlexService: true
